"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const pergunta1 = "Questão 1 - Defina o que é uma variável na programação." + "\n";
console.log(pergunta1, "R= Uma variável é..." + "\n");
const pergunta2 = "Questão 2 - Escreva com as suas palavras a diferença entre as declarações const, let e var e como elas podem ser aplicadas na prática." + "\n";
console.log(pergunta2, "R=" + "\n", "Var: A forma de declarar uma variável através do var é usado para declaração de variáveis com escopo global, o var possibilita a atualização e declaração novamente dentro do seu escopo;");
console.log("Let: Já com a utilização do let as variáveis tem escopo de bloco, podendo ser atualizada dentro do seu escopo, contudo, não é possível declarar novamente dentro do seu próprio escopo;");
console.log("Const: Esta forma de declarar variável, assim como o let, também têm escopo de bloco, contudo, o valor atribuído a uma varivável declarada com const não pode ser modificado, pois com o const não pode ocorrer atualização e nem declaração novamente dentro do seu escopo." + "\n");
const pergunta3 = "Questão 3 - Explique a diferença entre as variáveis do tipo objeto e lista." + "\n";
console.log(pergunta3, "R=");
console.log("Variável do tipo objeto=");
console.log("Variável do tipo lista=");
